export interface Api {
    ciudad_municipio:string;
    ciudad_municipio_nom:string;
    departamento:string;
    departamento_nom:string;
    edad:string;
    estado:string;
    fecha_de_notificaci_n:string;
    fecha_diagnostico:string;
    fecha_inicio_sintomas:string;
    fecha_recuperado:string;
    fecha_reporte_web:string;
    fuente_tipo_contagio:string;
    id_de_caso:string;
    pais_viajo_1_cod:string;
    pais_viajo_1_nom:string;
    per_etn_:string;
    recuperado:string;
    sexo:string;
    tipo_recuperacion:string;
    ubicacion:string;
    unidad_medida:string;
}
